install:
  - npm i -g npm && npm install

before_script:
  ## runs the 'start' script which
  ## boots our local app server on port 8080
  ## which cypress expects to be running
  ## -----------------------------------
  ## the '-- --silent' passes arguments
  ## to http-server which silences its output
  ## else our travis logs would be cluttered
  ## with output from HTTP requests
  ## https://docs.npmjs.com/cli/start
  ## https://github.com/indexzero/http-server
  ## ---------------------------------------
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - npm run dev -- --silent &

script:
  ## now run cypress headlessly
  ## and record all of the tests.
  ## Cypress will search for a
  ## CYPRESS_RECORD_KEY environment
  ## variable by default and apply
  ## this to the run.
  - $(npm bin)/cypress run --record --key 0ae8477a-1492-4fcd-bffc-cf84b29700f1

  ## alternatively we could specify
  ## a specific record key to use
  ## like this without having to
  ## configure environment variables
  ## - cypress run --record --key <your_record_key>
notifications:
  slack: calosearch:laHm03qpWkLRHO7jU2E4ZNXy
  webhooks:
    - https://discordapp.com/api/webhooks/372840550233276416/Dpme3s10AkJ3o5v4K5Dyg60wJvyhiwSVS4TEFCl33DpOOdQuzg5dzHFPf8ogw1WDAEg-
